#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run pre-commit
# npx lint-staged
# npm test                                              
# npm lint-staged
# npm lint staged ? 
npm run lint:fix
npm run test
